// lib/features/diary_entry/presentation/bloc/diary_form/diary_form_event.dart

import 'package:equatable/equatable.dart';

import '../../../domain/entities/mood.dart';

sealed class DiaryFormEvent extends Equatable {
  const DiaryFormEvent();

  @override
  List<Object?> get props => [];
}

/// Fired once when the form screen opens. Pass [entryId] to load an
/// existing entry for editing; leave it null to start a blank create form.
final class DiaryFormInitialized extends DiaryFormEvent {
  final String? entryId;

  const DiaryFormInitialized({this.entryId});

  @override
  List<Object?> get props => [entryId];
}

final class DiaryFormTitleChanged extends DiaryFormEvent {
  final String title;

  const DiaryFormTitleChanged(this.title);

  @override
  List<Object?> get props => [title];
}

/// Fired whenever the Quill document changes — content holds Delta JSON,
/// not plain text.
final class DiaryFormContentChanged extends DiaryFormEvent {
  final String content;

  const DiaryFormContentChanged(this.content);

  @override
  List<Object?> get props => [content];
}

final class DiaryFormDateChanged extends DiaryFormEvent {
  final DateTime date;

  const DiaryFormDateChanged(this.date);

  @override
  List<Object?> get props => [date];
}

final class DiaryFormMoodChanged extends DiaryFormEvent {
  final Mood? mood;

  const DiaryFormMoodChanged(this.mood);

  @override
  List<Object?> get props => [mood];
}

/// Fired when the font picker selects a family. Applies to the whole
/// entry (stored on the entity's `fontFamily` field), not per-selection
/// rich-text formatting.
final class DiaryFormFontFamilyChanged extends DiaryFormEvent {
  final String? fontFamily;

  const DiaryFormFontFamilyChanged(this.fontFamily);

  @override
  List<Object?> get props => [fontFamily];
}

/// Fired when the text-format panel's alignment control is changed.
/// Applies to the whole entry — both the title field (rendered via
/// `TextAlign` off this state field) and the Quill description (which
/// applies the corresponding `quill.Attribute.align` itself,
/// independently, since alignment is stored as Delta formatting for
/// the description but as a plain state field for the title).
///
/// [alignment] is one of `'left'`, `'center'`, `'right'`, `'justify'`,
/// matching the `String` values Quill's own alignment attributes use,
/// so this field can be compared directly against
/// `quill.Attribute.align`'s value without any translation.
final class DiaryFormAlignmentChanged extends DiaryFormEvent {
  final String alignment;

  const DiaryFormAlignmentChanged(this.alignment);

  @override
  List<Object?> get props => [alignment];
}

/// Fired when Bold/Italic/Underline are toggled from the T panel.
/// Applies to the whole entry (title + description), same as
/// [DiaryFormAlignmentChanged] — see `DiaryFormState.isBold` etc.
final class DiaryFormBoldChanged extends DiaryFormEvent {
  final bool isBold;

  const DiaryFormBoldChanged(this.isBold);

  @override
  List<Object?> get props => [isBold];
}

final class DiaryFormItalicChanged extends DiaryFormEvent {
  final bool isItalic;

  const DiaryFormItalicChanged(this.isItalic);

  @override
  List<Object?> get props => [isItalic];
}

final class DiaryFormUnderlineChanged extends DiaryFormEvent {
  final bool isUnderline;

  const DiaryFormUnderlineChanged(this.isUnderline);

  @override
  List<Object?> get props => [isUnderline];
}

/// Fired when a font size is picked in the T panel. `null` means
/// "Normal" (clear back to the document's default size).
final class DiaryFormFontSizeChanged extends DiaryFormEvent {
  final String? fontSize;

  const DiaryFormFontSizeChanged(this.fontSize);

  @override
  List<Object?> get props => [fontSize];
}

/// Fired when a color is picked (or cleared, passing `null`) in the
/// dedicated "Text color" panel. `null` means back to the default
/// color.
final class DiaryFormTextColorChanged extends DiaryFormEvent {
  final String? textColorHex;

  const DiaryFormTextColorChanged(this.textColorHex);

  @override
  List<Object?> get props => [textColorHex];
}

/// Fired after a gallery photo is inserted into the document, so the
/// denormalized `images` list stays in sync with what's actually in the
/// content.
final class DiaryFormImageAdded extends DiaryFormEvent {
  final String imagePath;

  const DiaryFormImageAdded(this.imagePath);

  @override
  List<Object?> get props => [imagePath];
}

/// Fired when a floating overlay photo is added (via the dedicated
/// overlay picker button, separate from the inline Quill image embed).
/// [id] is generated by the caller so the same value can be used
/// immediately as the new item's `ValueKey` before the bloc round-trips
/// the state update.
final class DiaryFormOverlayImageAdded extends DiaryFormEvent {
  final String id;
  final String path;
  final double x;
  final double y;

  const DiaryFormOverlayImageAdded({
    required this.id,
    required this.path,
    required this.x,
    required this.y,
  });

  @override
  List<Object?> get props => [id, path, x, y];
}

/// Fired continuously while dragging/pinching/rotating an overlay
/// image, and once more on gesture end — matches `TransformableItem`'s
/// `onUpdate` callback shape exactly so the widget layer can forward it
/// without any adapting.
final class DiaryFormOverlayImageTransformed extends DiaryFormEvent {
  final String id;
  final double x;
  final double y;
  final double scale;
  final double rotation;

  const DiaryFormOverlayImageTransformed({
    required this.id,
    required this.x,
    required this.y,
    required this.scale,
    required this.rotation,
  });

  @override
  List<Object?> get props => [id, x, y, scale, rotation];
}

/// Fired when an overlay image's delete handle is tapped.
final class DiaryFormOverlayImageRemoved extends DiaryFormEvent {
  final String id;

  const DiaryFormOverlayImageRemoved(this.id);

  @override
  List<Object?> get props => [id];
}

/// Fired when an overlay image is tapped to select it, or when
/// selection should be cleared (pass `null`) — e.g. tapping empty space
/// in the overlay layer.
final class DiaryFormOverlayImageSelected extends DiaryFormEvent {
  final String? id;

  const DiaryFormOverlayImageSelected(this.id);

  @override
  List<Object?> get props => [id];
}

/// Fired once a sticker has been downloaded/cached and should be added
/// to the canvas as a new floating overlay. [url] is the permanent
/// Supabase source (kept for recovery); [localPath] is the freshly
/// downloaded cache file used to render it immediately.
final class DiaryFormStickerAdded extends DiaryFormEvent {
  final String id;
  final String url;
  final String localPath;
  final double x;
  final double y;

  const DiaryFormStickerAdded({
    required this.id,
    required this.url,
    required this.localPath,
    required this.x,
    required this.y,
  });

  @override
  List<Object?> get props => [id, url, localPath, x, y];
}

/// Fired continuously while dragging/pinching/rotating a sticker, and
/// once more on gesture end — matches `TransformableItem`'s `onUpdate`
/// callback shape exactly, same as
/// [DiaryFormOverlayImageTransformed].
final class DiaryFormStickerTransformed extends DiaryFormEvent {
  final String id;
  final double x;
  final double y;
  final double scale;
  final double rotation;

  const DiaryFormStickerTransformed({
    required this.id,
    required this.x,
    required this.y,
    required this.scale,
    required this.rotation,
  });

  @override
  List<Object?> get props => [id, x, y, scale, rotation];
}

/// Fired when a sticker's delete handle is tapped.
final class DiaryFormStickerRemoved extends DiaryFormEvent {
  final String id;

  const DiaryFormStickerRemoved(this.id);

  @override
  List<Object?> get props => [id];
}

/// Fired when a sticker is tapped to select it, or when selection
/// should be cleared (pass `null`).
final class DiaryFormStickerSelected extends DiaryFormEvent {
  final String? id;

  const DiaryFormStickerSelected(this.id);

  @override
  List<Object?> get props => [id];
}

/// Fired when a background is chosen. Exactly one of [bgImagePath]
/// (bundled preset), [bgGalleryImagePath] (user's own photo), or
/// [bgLocalPath] (cached Supabase preset) is set per the app's
/// precedence rule (gallery > preset-local > preset-remote > color) —
/// the caller (diary_form_page) is responsible for nulling out the
/// other two based on `SelectedBackground.type` before dispatching.
final class DiaryFormBackgroundChanged extends DiaryFormEvent {
  final String? bgImagePath;
  final String? bgGalleryImagePath;
  final String? bgLocalPath;

  const DiaryFormBackgroundChanged({
    this.bgImagePath,
    this.bgGalleryImagePath,
    this.bgLocalPath,
  });

  @override
  List<Object?> get props => [bgImagePath, bgGalleryImagePath, bgLocalPath];
}

/// Fired when the background overlay tint's opacity and/or color is
/// adjusted via the form's settings icon. Both fields are always sent
/// together since the opacity settings sheet exposes them as one
/// control group, unlike [DiaryFormBackgroundChanged]'s
/// exactly-one-of-three shape.
///
/// [color] is `'white'`, `'black'`, or `null` for "Auto" (tint follows
/// the app's active theme automatically — see [OverlayTintUtils]).
final class DiaryFormOverlayOpacityChanged extends DiaryFormEvent {
  final double opacity;
  final String? color;

  const DiaryFormOverlayOpacityChanged({
    required this.opacity,
    required this.color,
  });

  @override
  List<Object?> get props => [opacity, color];
}

/// Fired when the user taps Save. The bloc itself guards against
/// duplicate submissions (see [DiaryFormBloc]) so rapid repeated taps of
/// this event are safe.
final class DiaryFormSubmitted extends DiaryFormEvent {
  const DiaryFormSubmitted();
}